version:            '3.1'
services:
  frontend:
    container_name: beergarden
    depends_on:
      - database
      - server
    image:          beergarden-frontend
    build:
    context:        ./frontend
    dockerfile:     frontend.dockerfile
    ports:
      - "80:80"
  database:
    container_name: postgres
    image:          postgres
    ports:
      - "27017:27017"
  server:
    container_name: clockmachine-api
    image:          clockmachine-api
    build:
    context:        ./backend
    dockerfile:     backend.dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
  web:
    image:          nginx:latest
    ports:- "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image:          php:7-fpm
