version:            '3.8'
services:
  database:
    container_name: postgres
    image:          postgres:14.1
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5430:5432"
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - ./src-php/:/var/www/html/
