version: '3.8'
services:
  database:
    build: ./docker/pgsql/
    container_name: postgres
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=Beergarden
    ports:
      - "5430:5432"
  web:
    build: ./docker/php/
    container_name: php_web
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - ./src-php/:/var/www/html/
